[package]
name = "vademecum"
version = "0.1.0"
authors = ["Iwan van der Kleijn <iwanvanderkleijn@gmail.com>"]

[dependencies]
lib = { path = "lib" }
ascii-rig = { path = "ascii-rig" }
transcript = { path = "transcript" }


[workspace]
